name: pda_scanner
description: This is a scanning plug-in for PDA(Dong ji Xiao ma ge) to Listen for scanned events and get results.
version: 0.1.4
author: Shusheng <leyansorosame@gmail.com>
homepage: https://github.com/leyan95/pda_scanner

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.shinow.pda_scanner
    pluginClass: PdaScannerPlugin